disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - control_statement
  # - line_length
  - identifier_name
opt_in_rules:
  - empty_count
included:
  - Source
excluded:
  - VendorFrameworks
  - Carthage
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift

force_cast: warning
force_try:
  severity: warning
line_length: 150
type_body_length:
  - 300
  - 400
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 4
  max_length:
    warning: 40
    error: 50
  excluded: iPhone
identifier_name:
  min_length:
    error: 4
  excluded:
    - id
    - up
    - URL
    - GlobalAPIKey
    - vc
    - vp
    - key
reporter: "xcode"
